name: 'Deploy slides to github pages'

on:
  push:
    branches:
      - main
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: echo slide=`npm run echo | awk '{print substr($0, index($0, "/"))}' | tail -n 1 | awk '{print substr($0, 2)}'` >> $GITHUB_ENV
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ env.slide }}

